# Generated by Django 6.0.5 on 2026-06-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('standard', 'Стандарт'), ('comfort', 'Комфорт'), ('superior', 'Улучшенный'), ('imperial', 'Империал')], default='standard', max_length=50, verbose_name='Категория')),
                ('room_number', models.CharField(help_text='Например: 101, 205, 310', max_length=10, verbose_name='Номер комнаты')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('photo1', models.ImageField(upload_to='rooms/', verbose_name='Фото 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Фото 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Фото 3')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
    ]
